# Generated by Django 3.0.8 on 2020-11-24 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=264)),
                ('bid_initial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image_url', models.URLField(blank=True, default='https://www.salonlfc.com/wp-content/uploads/2018/01/image-not-found-scaled-1150x647.png')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_watched', models.ManyToManyField(blank=True, null=True, related_name='auction_watched', to='auctions.Auction')),
                ('user_watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watcher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=264)),
                ('auction_commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_commented', to='auctions.Auction')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('auction_bided', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bided', to='auctions.Auction')),
                ('user_bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_product', to='auctions.Category'),
        ),
        migrations.AddField(
            model_name='auction',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
