# Generated by Django 3.0.8 on 2020-11-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201123_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auction_watched',
            field=models.ManyToManyField(blank=True, related_name='auction_watched', to='auctions.Auction'),
        ),
    ]
