# Generated by Django 3.0.8 on 2020-12-04 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201203_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auction_watched',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched', to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user_watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
