# Generated by Django 3.0.8 on 2020-12-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_winner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('bid',)},
        ),
    ]
